dist: xenial
os: linux
language: java
cache:
  directories:
  - "~/.m2"
branches:
  only:
  - master
  - development
install: ''
services:
- docker
before_install:
- chmod +x mvnw
- docker version
jobs:
  fast_finish: true
  include:
  - jdk: openjdk11
    env:
    - DESC="build with OPENJDK11"
    - USE_MAVEN_REPO="true"
    - CMD="mvn clean package"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
  - secure: bjbI2Dzd9/rtfiUEYa6hepvNdNIg3xFp/YS0RhrlyUIItLI2LnwWpT2tGQOyTD7x2fyamodHjGOW7N8kOEZp5UliqwMLJE8VoJ5C8S/y99ljv/DTFTnXV4PdDDDPmREqi8vFZuNkfitffWWVCUtsKVYXQVDdOJ0a38Eid8jiv1huPhRP+dAzxdFEFVFvphYw7y71QZJjid7Amw/fx8b3wuO948eCLn4bE4TyS67k3RUb3exarAzxrip/Us97H8eXILrRbvm38WRhY5XOFd+4GqYJA/229FO3PhGibPPyQ3XnAeVjSvbDaEYliIP7o4RnfDh7pK0E/VWvTLk95XUp3iOfTPC+cHjKPbdJgwZBVWwr7ALs3Chlu+OfTVlEZc+F7YWcJYPNnLTXygKqFbeS+SQAKoR8YZ+tNLKYup+ll87sekvu3Dx/p17k0XG2t0eRjLuh3eKxUG9y6B/mXV44epyCuJz+A8NmprFNPjziERTrnXqIKHJX1fxY+iK7AgPGBRjSt+VSrtNI+kV1ndFq7+fpdLXBt9i6RkDY9RU1SjJP1ZuiDuiAwSeFmTEmGEeG/49uA79Gm+4bGNpgKRWufgoLnYfjGp2e4DTgHBa/hswWhOvqc2vfzPoeIouDN1tFgFktHhJh+sRxJGDPFF5YdF5yok5bd2GJacQ3XJvvrgw=
  - secure: TKdlNrPPtsBhc1ypAFtVuW4nY4buoczPYaKI8NxXZ5abWielI44Sf3yH32VGNLLSGzsAfOv5yuW61er/L+O9oBVgz2N5ry+MhS6KMD5aumOflM5pv5axDs2zMGvEif5k9Q+MNtAzwsUjkiAJiKOIFzKDJaTp6V4E5o1qk5CUu2IJI+gHhnYCUBRU+WDrc1RRE3BxFncGuLxSzAng03DkIyj0Y4Y7kFUSnRvGieHebtwMDhb9trt7B1IUvDVF7B4q5XwhQJGZNCAV1KXWwzKC1sKiaktO6i7BNfumKLtExQfjt+yLG6cz3KgmyI3jshnSIFpcyJYLWdP9gQ3vr6bCR6Rsl8OAW4GMpmCCUnYwFKLwsffBF67R65Bt23wpD5NxKflxChiJ7pPUD8AKn5FKIMtbS1LjRU63Q5T04gysN9ERCSUvVUc5N3ANRTnTw0+IXgeq2HPcSWOZJ4JAR+xyOSV9MmP0eVz+w6YdAoW5Hf9ti4f/r9dqW0gxo1S9ws6xPfXW7T9KF1MD4b9XzLya7ti20jAqS16SDT8YOxlWI59fK0oNhF33nC2nNDKiA3hFz25Ntqro/6fNVxyxKkI4woNSaNGN1hF478KGORDDSG+hv22DRGKDcmOmYrtHCRvy80vIyIq7NQuclLQoP30/n//fEUTgr8jscZdK8UgoOCE=
script:
- ./mvnw clean package -B
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "development" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- export IMAGE_NAME=sombose/file-uploader
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
